### PR TITLE
Add User Audio Detection

### PR DESCRIPTION
**Pull request by ai-are-better-than-humans**
This would allow any custom provided audio files to be automatically detected

### CODE REVIEW

**Comment by blue-fish** [comment]
Hi @ai-are-better-than-humans , thank you for your interest in contributing to the project. I reviewed the commit history and noticed that UserAudio is added in ec9658aad21178c90c5f673778c2c0051e33ad35 and then removed shortly thereafter in 41c37b273fc1c150ceeab0906a6c1282163d9d5b . It seems @CorentinJ forgot to update the documentation in demo_toolbox.py along with the second commit.

https://github.com/CorentinJ/Real-Time-Voice-Cloning/blob/8f71d678d2457dffc4d07b52e75be11433313e15/demo_toolbox.py#L14-L18

My recommendation is to remove the mention of UserAudio in demo_toolbox.py, instead of adding the feature back in. What do you think?

**Comment by ai-are-better-than-humans** [comment]
How would someone provide custom audio files if `UserAudio` was removed? either remove it and add the description on how to do this specifically in the readme, or keep it, add this function, and maybe also update the readme to mention UserAudio

**Comment by blue-fish** [comment]
> How would someone provide custom audio files if `UserAudio` was removed?

The "browse" button in the toolbox opens up a file browser to select any audio file that's available on the computer. Though that is most efficient with small numbers of files and not the 400 files you mentioned in #528.

**Comment by ai-are-better-than-humans** [comment]
Yes, so for larger datasets you might want to leverage the 'auto select next' next feature for bigger datasets.

**Comment by blue-fish** [comment]
I plan to leave the pull request unmerged and see if anyone else requests this. To improve maintainability of the code we need to avoid adding rarely-used features. In the meantime, UserAudio is working for you and anyone else who stumbles across this pull request.

**Comment by blue-fish** [comment]
Decided to take the approach in https://github.com/CorentinJ/Real-Time-Voice-Cloning/pull/527#issuecomment-693227456 and update the documentation to reflect the deleted feature.

@ai-are-better-than-humans I do appreciate you taking the initiative to write a fix for a problem that you found. We would welcome additional contributions, though it would be preferable to first open an issue and validate the need to fix something before going ahead with it.

**Pull request closed without merging**
