### PR TITLE
wandb instrumentation

### PR DESCRIPTION
**Pull request by syllogismos**
I did wandb instrumentation of this repo, to log histograms, plots, audios while training. You can see the resulting report [here](https://app.wandb.ai/syllogismos/real-time-voice-cloning/reports?view=syllogismos%2FTraining%20Report)

## Encoder Training results
image

## Synthesizer Training results
image
image

## Vocoder Training results
image

### CODE REVIEW

**Comment by daciansolgen** [comment]
how did you get this to work?? i cant even install the software :(

**Comment by syllogismos** [comment]
Hey, I trained p2.xlarge EC2 instance, used amazon deep learning AMI as base machine, I can give you the conda environment file if you needed.

Also I trained on part of the training dataset. And even with part of the training dataset, I needed a 1TB harddrive to save all the generated models, data of encoder, synthesizer and vocoder models.

**Comment by syllogismos** [comment]
Here is the conda environment file https://gist.github.com/syllogismos/0b3097c7714ce6119db500a3fcdcc8dd

you can install this environment using this command `conda env create -f environment.yml`

It has additional slack and twitter pip packages installed as I tried building slack and twitter mention bots that reply with an audio of what you typed automatically. Will post the code here.

**Comment by blue-fish** [comment]
@CorentinJ Requesting that this PR be closed without merging. Please see my review for rationale.

**Comment by CorentinJ** [comment]
The PR is riddled with unnecessary code anyway.

**Comment by syllogismos** [comment]
Thank you for responding and comments @CorentinJ @blue-fish This is a really cool project.

The initial pull request only has the wandb instrumentation. After that I saw this repo is not supported anymore. I wasn't hoping that the slackbot and twitter bot to be merged into this. I can do a separate pull request with only wandb instrumentation if anyone is interested. 

I did the twitterbot/slackbot as a fun experiment. I used the trained model you provided for the bots, but the results are okay. Does the voice have to be in the training dataset? I wanted to generate people's mentions on twitter into the voice of Stephen Fry. And I used 20 minutes of his voice. I don't know, the cloned voice seemed really monotonous, and isn't capturing the gaps between the words, it seems like the gaps also has some information regarding a persons voice? I don't know. I didn't really check out other voice cloning projects. Do you have any suggestions on getting better results?

Thank you.

**Comment by CorentinJ** [comment]
What you're looking for is the basic tacotron without the SV2TTS addition. Take a pretrained model and finetune it on your 20 minutes of data. See [here](https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/364#issuecomment-652009580) for a list of links to other repos that will fill this task better.

Yeah wandb could be added, although I personally am not a fan of their aggressive marketing towards an unfinished product. I don't think it's very much worth it, as missing visualization features could simply be added to visdom (if you think there are any) instead.

**Pull request closed without merging**
