### PR TITLE
Convert embeds to np array

### PR DESCRIPTION
**Pull request by Ca-ressemble-a-du-fake**
To remove the warning that appears while training

### CODE REVIEW

**Comment by blue-fish** [comment]
Please revert the change to symbols.py

**Comment by blue-fish** [comment]
`symbols.py` is still showing up as a changed file. You need to restore it to its original state. We can't merge that change because it would break compatibility with the pretrained model.

**Comment by Ca-ressemble-a-du-fake** [comment]
I haven't noticed your reply so far. I'll do it. I have discovered interesting thing also in between.

**Comment by Ca-ressemble-a-du-fake** [comment]
So I just removed the added symbols.

**Review by blue-fish — APPROVED** [review]

**Pull request merged**
